Redux
victorokoroji/bookstore pull request #2
Opened 2022-04-05 16:26 UTC by vickymarz

_In these project,_ 

- Created redux store
- Add actions for books and categories
- dispatch actions to store

2022-04-05 17:25 UTC, Cathella requested changes
## 🟡 Status: Changes Required 🛑

### Hi @vickymarz 👋🏻, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## To Highlight 👏🏻

✅ No linter errors.
✅ You used correct Github Flow.
✅ Great use of the ducks pattern.


## Required Changes ♻️
_Check the comments under the review._

- [ ] When I load the project on a local server, I see a series of console errors land a blank page. Please fix the console errors.

![image](https://user-images.githubusercontent.com/4247740/161814474-ce96bf77-97c3-4a33-926a-e7511ed31e0c.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

![i-guess-we-have-to-give-it-another-shot-liz-lemon](https://user-images.githubusercontent.com/4247740/161814574-f4c379a7-37ad-43c9-b233-eaf4750ed68f.gif)


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-05 17:25 UTC, Cathella commented on src/redux/configureStore.js
> +import categoryReducer from './categories/categories';
- [ ] Please rename this to `categoriesReducer` as defined in the referenced `categories.js`

2022-04-05 17:25 UTC, Cathella commented on src/redux/books/books.js
> +      };
- [ ] HINT: For the remove book action you can use filter by the id key to make sure that a book is removed from an array - i.e.: 
```
   return state.filter(book => book.id !== id);
```

2022-04-05 18:54 UTC, vickymarz commented on src/redux/books/books.js
> +      };
This is great. I will update this. Thanks

2022-04-05 18:54 UTC, vickymarz commented on src/redux/configureStore.js
> +import categoryReducer from './categories/categories';
Thanks for spotting this.

2022-04-06 00:29 UTC, BrianSammit approved these changes
# STATUS: APPROVED :green_circle: :clap: 

Hello @vickymarz, 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

TO HIGHLIGHT:

- Your project is professional 
- Your repo is professional 
- Well structured files 


Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-06 00:59 UTC, merged